from turtle import Turtle,Screen
screen = Screen()
screen.bgcolor("black")
timmy = Turtle()
timmy.color("red")
timmy.width(3)
#timmy.speed("fast")
radius =100
timmy.circle(radius)
timmy.lt(39)
timmy.fd(115)
timmy.lt(72)
timmy.fd(115)
timmy.lt(72)
timmy.fd(115)
timmy.lt(72)
timmy.fd(115)
timmy.lt(72)
timmy.fd(115)
screen.exitonclick()
